### ISSUE TITLE
Use sparkpost library under the hood?

### ISSUE THREAD

**Issue by richleland** [SparkPost/bamboo_sparkpost#5]
Should we use the [sparkpost](https://github.com/SparkPost/elixir-sparkpost) library under the hood? I'm not super familiar wth Bamboo and how the adapters need to be constructed yet, so this is more of an investigative ticket. That said it can have implications on how we forge ahead with updates.

**Comment by genericlady** [comment]
@richleland I think that's a great idea, the library works 100% for sure so why not just use it? We only need to implement it in the [SparkpostAdapter.delivery/2](https://github.com/genericlady/bamboo_sparkpost/blob/master/lib/bamboo/adapters/sparkpost_adapter.ex#L48)

Also, ultimately this is using [HTTPoison.post!/3](https://github.com/genericlady/bamboo_sparkpost/blob/master/lib/bamboo/adapters/sparkpost_adapter.ex#L166), so we can just forgo all that in place of the sp library.

As long as we use `Sparkpost.Transmission.send` everything will be great. I'll add the Sparkpost library to the packages and will update accordingly. There's more going on [here in the Sparkpost library](https://github.com/SparkPost/elixir-sparkpost/blob/master/lib/endpoint.ex#L35) than inside the adapter.

**Comment by richleland** [comment]
Awesome - I say we keep this ticket simple, add the deps, close it out. We can do the implementation in another ticket. Shoot over a PR whenever you've got it. Thanks!

**Comment by genericlady** [comment]
Closing issue to keep tickets small. Nailing down issues in a test project and will create new tickets.
